#!/bin/sh

source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__main"

echo "$(script_name -m) Starting the Minecraft server..."

java -Xmx5120M -Xms5120M -jar server.jar nogui
