#!/bin/sh

source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__md_text"
source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__script_name"

FILE_NAME='./../data.json'

if [ $# -eq 0 ]; then
	echo "$(script_name -m) $(script_name) <ip> $(md_text '|' -b) Updates server IP" && \
	echo "$(script_name -m) $(script_name) -s   $(md_text '|' -b) Stops the server" && \
	exit
fi

if [[ "$1" == '-s' ]]; then
	NEW_IP="Server Down"
	COMMIT_MESSAGE="Took the server down on \`server.kqpa.me\`"
else
	NEW_IP="$1"
	COMMIT_MESSAGE="Updated the server IP address to \`$NEW_IP\`"
fi

printf "$(script_name -m) Replacing IP in '$(md_text "$FILE_NAME" -b)' with '$(md_text "$NEW_IP" -b)'... "

if (
: > $FILE_NAME

cat <<EOT >> $FILE_NAME
{
	"text": "$NEW_IP"
}
EOT

git add -A :/ && git pull --quiet && git commit -m "$COMMIT_MESSAGE" --quiet && git push --quiet

); then
	echo "OK."
else
	exit 1
fi