#!/usr/bin/env bash

source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__main"
discord.sh() { 
source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__discord" 
}

FILE_NAME='./../data.json'
NEW_IP="$1"
NEW_COMMIT_MESSAGE="Updated the server IP address to \`$NEW_IP\`"
DOWN_MESSAGE="Server Down"
DOWN_COMMIT_MESSAGE="Took the server down on \`server.kqpa.me\`"

if [ $# -eq 0 ]; then
	echo "$(script_name -m) $(script_name) <ip> $(md_text '|' -b) Updates server IP" && \
	echo "$(script_name -m) $(script_name) -s   $(md_text '|' -b) Stops the server" && \
	exit 1
fi

: > $FILE_NAME

if [ $1 = "-s" ]; then

cat <<EOT >> $FILE_NAME
{
	"text": "$DOWN_MESSAGE"
}
EOT

git add -A :/ && git pull && git commit -m "$DOWN_COMMIT_MESSAGE" && git push
echo "$(script_name -m) successfully replaced the IP in '$(md_text "$FILE_NAME" -b)' with '$(md_text "$DOWN_MESSAGE" -b)'"

else

cat <<EOT >> $FILE_NAME
{
	"text": "$NEW_IP"
}
EOT

git add -A :/ && git pull && git commit -m "$NEW_COMMIT_MESSAGE" && git push
echo "$(script_name -m) successfully replaced the IP in '$(md_text "$FILE_NAME" -b)' with '$(md_text "$NEW_IP" -b)'"

fi

# "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/mc::discord" $NEW_IP

echo "$(script_name -m) Sending IP update to Discord..."

WEBHOOK_URL="https://discord.com/api/webhooks/1003357285789220924/ZMRoKdPGp-m--UAE2oGactFx6pq6rgM7rGqgwpT4Fo75PQWxim_v4hb_p8akN80e3EQp"
TITLE="IP adresi güncellendi"
if [[ "$NEW_IP" == "-s" ]]; then
	DESCRIPTION="• **Sunucu şu anda __kapalı__**."
else
	DESCRIPTION="• **Sunucunun IP adresi güncellendi**:\n__\`$NEW_IP\`__"
fi
COLOR="0xfcba03"
IMAGE_URL="https://i.imgur.com/hIOfppt.png"
LINK="https://server.kqpa.me"
AUTHOR="Blaze SMP"
FOOTER="Otomatik Bildirim"

discord.sh                              \
    --webhook-url       "$WEBHOOK_URL"  \
    --title             "$TITLE"        \
    --description       "$DESCRIPTION"  \
    --color             "$COLOR"        \
    --url               "$LINK"         \
    --author            "$AUTHOR"       \
    --author-url        "$LINK"         \
    --author-icon       "$IMAGE_URL"    \
    --thumbnail         "$IMAGE_URL"    \
    --footer            "$FOOTER"       \
    --timestamp
