#!/bin/sh

source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__misc/__misc"

FILE_NAME='./../data.json'
NEW_IP="$1"
NEW_COMMIT_MESSAGE="Updated the server IP address to \`$NEW_IP\`"
DOWN_MESSAGE="Server Down"
DOWN_COMMIT_MESSAGE="Took the server down on \`server.kqpa.me\`"

if [ $# -eq 0 ]; then
	echo "$(script_name -m) $(script_name) <ip> $(md_text '|' -b) Updates server IP" && \
	echo "$(script_name -m) $(script_name) -s   $(md_text '|' -b) Stops the server" && \
	exit 1
fi

: > $FILE_NAME

if [ $NEW_IP = "-s" ]; then

cat <<EOT >> $FILE_NAME
{
	"text": "$DOWN_MESSAGE"
}
EOT

git add -A :/ && git pull && git commit -m "$DOWN_COMMIT_MESSAGE" && git push
echo "$(script_name -m) successfully replaced the IP in '$(md_text $FILE_NAME -b)' with '$(md_text $DOWN_MESSAGE -b)'"

else

cat <<EOT >> $FILE_NAME
{
	"text": "$NEW_IP"
}
EOT

git add -A :/ && git pull && git commit -m "$NEW_COMMIT_MESSAGE" && git push
echo "$(script_name -m) successfully replaced the IP in '$(md_text $FILE_NAME -b)' with '$(md_text $NEW_IP -b)'"

fi

exit 0
