#!/usr/bin/env bash

source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__md_text"
source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__script_name"
source "$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/__lib/__discord" 

if [ $# -eq 0 ]; then
	echo "$(script_name -m) $(script_name) <ip> $(md_text '|' -b) Updates server IP" && \
	echo "$(script_name -m) $(script_name) -s   $(md_text '|' -b) Stops the server" && \
	exit
fi

NEW_IP="$1"
WEBHOOK_URL="https://discord.com/api/webhooks/1003357285789220924/ZMRoKdPGp-m--UAE2oGactFx6pq6rgM7rGqgwpT4Fo75PQWxim_v4hb_p8akN80e3EQp"
TITLE="IP adresi güncellendi"
COLOR="0xfcba03"
IMAGE_URL="https://i.imgur.com/hIOfppt.png"
LINK="https://server.kqpa.me"
AUTHOR="Blaze SMP"
FOOTER="Otomatik Bildirim"
if [[ "$NEW_IP" == '-s' ]]; then DESCRIPTION="• **Sunucu şu anda __kapalı__**."; \
                            else DESCRIPTION="• **Sunucunun IP adresi güncellendi**:\n__\`$NEW_IP\`__"; fi

printf "$(script_name -m) Sending IP update to Discord... "

if (
        discord.sh                              \
            --webhook-url       "$WEBHOOK_URL"  \
            --title             "$TITLE"        \
            --description       "$DESCRIPTION"  \
            --color             "$COLOR"        \
            --url               "$LINK"         \
            --author            "$AUTHOR"       \
            --author-url        "$LINK"         \
            --author-icon       "$IMAGE_URL"    \
            --thumbnail         "$IMAGE_URL"    \
            --footer            "$FOOTER"       \
            --timestamp
); then
    echo "OK."
else
    exit 1
fi
